; Automatically generated by /usr/lib/cumulus/update-ports.
; Sun Mar 22 08:32:54 2026
; Do not edit.


;;;
;;; Constants
;;;

;;;
;;; The link scan base address points to an array of per-port data (32
;;; elements, 2 bytes each) which is continually updated by the main CPU's
;;; linkscan task.
LINKSCAN_P         equ    0x80 ; port data base address

;;; bits in the port data fields
LINKSCAN_LINK      equ    0x0  ; link down/up
LINKSCAN_TX        equ    0x4  ; transmitted packet
LINKSCAN_RX        equ    0x5  ; received packet

;;;
;;; The port status base address points to an array of per-port data (32
;;; elements, 2 bytes each) which is continually updated by the switch chip.
;;; This address is implied by port related op codes
PORTSTATUS_P       equ    0x00 ; port status base address

;;; bits in the linkscan port status fields
PORTSTATUS_RX      equ    0x0  ; received packet
PORTSTATUS_TX      equ    0x1  ; transmitted packet
PORTSTATUS_COLL    equ    0x2  ; collision
PORTSTATUS_SPEED_C equ    0x3  ; 100Mbps
PORTSTATUS_SPEED_M equ    0x4  ; 1Gbps
PORTSTATUS_DUPLEX  equ    0x5  ; half/full duplex
PORTSTATUS_FLOW    equ    0x6  ; flow control capable
PORTSTATUS_LINKUP  equ    0x7  ; link down/up
PORTSTATUS_LINKEN  equ    0x8  ; link disabled/enabled
PORTSTATUS_ZERO    equ    0xe  ; always 0
PORTSTATUS_ONE     equ    0xf  ; always 1

;;;
;;; Blink constants
TICKS_PER_SEC      equ    30   ; LED program runs at 30Hz


;;;
;;; Platform-specific defines
TICKS_PER_BLINK    equ    3    ; 0 to alternate every cycle (15Hz)
NUM_LEDS           equ    64


;;;
;;; Variables
;;;
;;; Addresses 0xa0 to 0xff are initialized to zero and usable by the program.
;;;

;;;
;;; Keep track of blink state, modified each cycle as a timer
BLINK_TICKS_P      equ    0xf0
BLINK_STATE_P      equ    0xf1


main:
        
        ld      a,6
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,5
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,8
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,7
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,30
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,31
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,32
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,29
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,36
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,35
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,34
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,33
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,28
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,27
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,26
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,25
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,23
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,24
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,21
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,22
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,16
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,15
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,14
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,13
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,10
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,9
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,12
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,11
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,19
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,20
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,17
        call    set_led_AcctonAS5610_52XSFPp
        ld      a,18
        call    set_led_AcctonAS5610_52XSFPp

        call blink_update_state
        send NUM_LEDS


blink_update_state:
        ld      a,(BLINK_TICKS_P)
        cmp     a,0
        jz      blink_toggle
        dec     a
        ld      (BLINK_TICKS_P),a
        ret
blink_toggle:
        ld      a,(BLINK_STATE_P)
        xor     a,0x01
        and     a,0x01
        ld      (BLINK_STATE_P),a
        ld      a,TICKS_PER_BLINK
        ld      (BLINK_TICKS_P),a
        ret


;;; AcctonAS5610_52XSFPp
;;;
;;; Two bits per port:
;;;
;;; 1st bit pushed on stack controls amber LED:
;;; 0 - off
;;; 1 - on
;;;
;;; 2n bit pushed on stack controls green LED:
;;; 0 - off
;;; 1 - on
;;;
;;; We will only use green LED.  1st bit pushed is always zero to
;;; disable amber LED.
set_led_AcctonAS5610_52XSFPp:
	port 1
	pushst PORTSTATUS_ZERO
	pack

        port    a
        ld      b,LINKSCAN_P
        add     b,a
        ld      b,(b)
        tst     b,LINKSCAN_TX
        push    cy
        tst     b,LINKSCAN_RX
        push    cy
        tor
        push    (BLINK_STATE_P)
        tand
        tinv                    ; flash off with activity
        pushst  PORTSTATUS_LINKEN
        tand
        pack

        ret

