onie_version=2017.02.00.07
onie_vendor_id=259
onie_platform=powerpc-accton_as5610_52x-r0
onie_machine=accton_as5610_52x
onie_machine_rev=0
onie_arch=powerpc
onie_config_version=0
onie_build_date="2017-06-06T10:47+0800"
onie_partition_type=
onie_kernel_version=3.2.69
onie_firmware=
onie_switch_asic=bcm
onie_skip_ethmgmt_macs=no
